---

- hosts: containers
  gather_facts: False
  remote_user: benjamin
  become: yes
  become_user: root
  become_method: sudo


  tasks:
          - name: Install Python
            raw: yum update -y || yum install -y python

          - name: sharing pub key
            authorized_key: user=benjamin
                            exclusive=no
                            key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}" 

